"""add settings table

Revision ID: 26ce4d893d2d
Revises: 436dc83ce3d5
Create Date: 2026-06-03 00:20:20.088634
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '26ce4d893d2d'
down_revision: str | None = '436dc83ce3d5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('highlight_r', sa.Integer(), nullable=False),
    sa.Column('highlight_g', sa.Integer(), nullable=False),
    sa.Column('highlight_b', sa.Integer(), nullable=False),
    sa.Column('highlight_effect', sa.String(), nullable=False),
    sa.Column('id', sa.String(length=15), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    # ### end Alembic commands ###
