"""add icon to devices

Revision ID: cbc7d7cdf904
Revises: 26ce4d893d2d
Create Date: 2026-06-06 01:55:51.071076
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'cbc7d7cdf904'
down_revision: str | None = '26ce4d893d2d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('icon', sa.String(), nullable=False, server_default='')
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_column('icon')

    # ### end Alembic commands ###
